apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  # 파드 교체 전략: 기존 파드를 먼저 종료하여 자원을 확보한 후 새 파드를 생성
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      # 파드를 eks-app-node 노드 그룹에 배치
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-app-node
      containers:
      - name: jellyfin
        # GitHub Action이 최신 이미지 SHA 값으로 자동 업데이트합니다.
        image: 635014547592.dkr.ecr.ap-northeast-2.amazonaws.com/my-ecr-app:7b6172e8a12b74c13586f4ceee91b75e4d8792d1
        ports:
        - containerPort: 8096
          name: http
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8096"
        # Pending을 해결하기 위해 리소스 예약량을 최소화했습니다.
        resources:
          requests:
            cpu: "50m"      # 최소 CPU 요구량 하향
            memory: "128Mi"  # 최소 메모리 요구량 하향
          limits:
            cpu: "500m"
            memory: "1Gi"

---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8096
  type: LoadBalancer
