apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  revisionHistoryLimit: 1  # 지저분한 RS 기록을 1개만 남기고 자동 정리합니다.
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-app-node
      containers:
      - name: jellyfin
        # GitHub Action에서 빌드된 최신 이미지를 사용합니다.
        image: 635014547592.dkr.ecr.ap-northeast-2.amazonaws.com/my-ecr-app:5422c7752eaf196f198c427e3cb270f0ab6524de
        ports:
        - containerPort: 8096
        resources:
          requests:
            cpu: "300m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
        # 이제 웹 클라이언트가 포함되어 있으므로 실제 헬스체크 경로를 바라봅니다.
        startupProbe:
          httpGet:
            path: /health
            port: 8096
          initialDelaySeconds: 20  # 초기 구동 시간을 넉넉히 줍니다.
          periodSeconds: 10
          failureThreshold: 15
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    port: 80         # 외부 접속 포트
    targetPort: 8096 # 컨테이너 내부 포트
  type: LoadBalancer
