apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  revisionHistoryLimit: 1 # 지저분한 RS 자동 정리
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      nodeSelector:
        eks.amazonaws.com/nodegroup: eks-app-node
      containers:
      - name: jellyfin
        image: 635014547592.dkr.ecr.ap-northeast-2.amazonaws.com/my-ecr-app:ba4f2c919b86a165f8027cce228d2bdcd90cd2db
        ports:
        - containerPort: 8096
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8096"
        # 웹 클라이언트 없이 서버만 띄울 때 서버가 죽지 않도록 체크 방식을 변경
        startupProbe:
          tcpSocket:
            port: 8096
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 20
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "1000m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-service
  namespace: jellyfin
spec:
  selector:
    app: jellyfin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8096
  type: LoadBalancer
