apiVersion: v1
kind: Namespace
metadata:
  name: media
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-api-sa
  namespace: media
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::635014547592:role/eks-media-api-s3-role