apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-efs
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-jellyfin-sc
  resources:
    requests:
      storage: 5Gi
