apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-jellyfin-sc
  resources:
    requests:
      storage: 50Gi
